export const languages = [ 
  "Arabic", "Basque", "Bengali", "Bulgarian", "Dutch", "English", "Estonian", 
  "Finnish", "French", "German", "Hausa", "Hebrew", "Hindi", "Hungarian", 
  "Igbo", "Italian", "Kazakh", "Kannada", "Khmer", "Malay", "Malayalam", 
  "Māori", "Mandarin Chinese", "Persian", "Polish", "Portuguese", "Russian", 
  "Spanish", "Swahili", "Swedish", "Tagalog", "Tamil", "Telugu", "Turkish", 
  "Ukrainian", "Urdu", "Vietnamese", "Yoruba", "Zulu"
]

export const il8n = {
  "Arabic": "ar-SA",
  "Basque": "eu-ES",
  "Bengali": "bn-BD",
  "Bulgarian": "bg-BG",
  "Dutch": "nl-NL",
  "English": "en-US",
  "Estonian": "et-EE",
  "Finnish": "fi-FI",
  "French": "fr-FR",
  "German": "de-DE",
  "Hausa": "ha-NG",
  "Hebrew": "he-IL",
  "Hindi": "hi-IN",
  "Hungarian": "hu-HU",
  "Igbo": "ig-NG",
  "Italian": "it-IT",
  "Kazakh": "kk-KZ",
  "Kannada": "kn-IN",
  "Khmer": "km-KH",
  "Malay": "ms-MY",
  "Malayalam": "ml-IN",
  "Māori": "mi-NZ",
  "Mandarin Chinese": "zh-CN",
  "Persian": "fa-IR",
  "Polish": "pl-PL",
  "Portuguese": "pt-PT",
  "Russian": "ru-RU",
  "Spanish": "es-ES",
  "Swahili": "sw-KE",
  "Swedish": "sv-SE",
  "Tagalog": "tl-PH",
  "Tamil": "ta-IN",
  "Telugu": "te-IN",
  "Turkish": "tr-TR",
  "Ukrainian": "uk-UA",
  "Urdu": "ur-PK",
  "Vietnamese": "vi-VN",
  "Yoruba": "yo-NG",
  "Zulu": "zu-ZA"
}
